### ISSUE TITLE
Error in Load Model

### ISSUE THREAD

**Issue by metaphorz** [mehdidc/feed_forward_vqgan_clip#19]
Two issues found:

(1) A Restart Runtime occurs on !pip install requirements.txt . This, in turn, resets the
current directory to /current. But even after manually updating the current directory....

(2) Under Load Model: ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZN3c106ivalue6Future15extractDataPtrsERKNS_6IValueE

**Comment by mesw** [comment]
I have tried to run the notebook and also failed.

```
ImportError                               Traceback (most recent call last)
<ipython-input-10-9274c6da60ac> in <module>()
      3 import clip
      4 get_ipython().magic('cd feed_forward_vqgan_clip')
----> 5 from main import load_vqgan_model, CLIP_DIM, clamp_with_grad, synth
      6 import torchvision
      7 

10 frames
/usr/local/lib/python3.7/dist-packages/torchtext/vocab.py in <module>()
     11 from typing import Dict, List, Optional, Iterable
     12 from collections import Counter, OrderedDict
---> 13 from torchtext._torchtext import (
     14     Vocab as VocabPybind,
     15 )

ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZN3c106ivalue6Future15extractDataPtrsERKNS_6IValueE
```

**Comment by mehdidc** [comment]
Hi, thanks for reporting this, for 2) it seems to be an error with the new PyTorch (1.10), I will fix it and let you know.

**Comment by mehdidc** [comment]
2) is fixed, please try again

**Comment by mesw** [comment]
I just tried it, the notebook works now.

This is so much faster than training each input. Thanks a lot!

**Comment by mehdidc** [comment]
Cool! thanks for the update

**Comment by metaphorz** [comment]
I just ran the colab notebook on the site. Had to restart runtime in an early cell.
Then, I get the following. Am I missing something?


ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-3-9179b795392c> in <module>()
      2 import torch
      3 import clip
----> 4 from main import load_vqgan_model, CLIP_DIM, clamp_with_grad, synth
      5 import torchvision
      6 

ModuleNotFoundError: No module named 'main'

**Comment by mehdidc** [comment]
Hi @metaphorz, it's probably because you needed to run the cell `cd feed_forward_vqgan_clip` again after restarting runtime

**Comment by amirham** [comment]
@mehdidc I'm getting the "ImportError: /usr/local/lib/python3.7/dist-packages/torchtext/_torchtext.so: undefined symbol: _ZTVN5torch3jit6MethodE" at the moment, might be the same cause as last time?

EDIT: It worked today, not sure if you fixed something behind the scenes or what, but I guess you can ignore this for now.

**Comment by mehdidc** [comment]
@amirham Yes I was fixing it indeed :), works now, thanks for mentioning it
